export const ROUTES = {
    login: '/login',
    users: '/users',
    user: '/user',
    posts: '/posts',
    post: '/post',
    home: '/',
    registrazione: '/registrazione',
    profilo: '/profilo',
    sub: '/sub',
    createPost: '/createPost',
    createUser: '/createUser',
    updatePost: '/updatePost',
    updateUser: '/updateUser',
}

export const SIDEBAR_LINK = {
    users: ROUTES.users,
    user: ROUTES.user,
    posts: ROUTES.posts,
    post: ROUTES.post,
    home: ROUTES.home,
    registrazione: ROUTES.registrazione,
    profilo: ROUTES.profilo,
    sub: ROUTES.sub,
    createPost: ROUTES.createPost,
    createUser: ROUTES.createUser,
    updatePost: ROUTES.updatePost,
    updateUser: ROUTES.updateUser,
}